#!/bin/bash
########################################################################
## Usage: runpy <script.py>
## runs the script.py and outputs to log.<script> 
## You'll be prompted for alternate log file name, but pressing enter
## causes it to default. Stdin and Stderr and redirected and the process
## is disowned, freeing up the terminal for other uses.
########################################################################

if test -z $1
then
	echo "Usage: runpy <script.py>, outputs directed to log.<script>"
#	echo 'Select Python input'
#	read file (uncomment this to read in a variable)
else
	file=$1
fi

echo Running ${file}
out=log.${file%%.py} #removes .py extension

# Ask for non default output location
echo Enter output name \(defaults to ${1}\)
read change
if test -z ${change}
then
	echo Default log selected
else
	out=${change}
fi

# Run and output
python ${file} > ${out} 2>&1 & disown
echo Stdin and stderr directed to ${out}
